### ISSUE TITLE
Allow gitlab bot to only notify on unsuccessful builds

### ISSUE THREAD

**Issue by mpauly** [Requilence/integram#10]
It would be extremly helpful if the Gitlab bot could be configured to just notify on failed builds only.
The relevant field `BuildStatus` is already checked here https://github.com/Requilence/integram/blob/master/services/gitlab/gitlab.go#L738

One would mainly need to add a command that allows to switch between displaying all builds and failed builds only.

**Comment by Requilence** [comment]
@mpauly Hi! Good suggestion. Will implement it in a few days

**Comment by mpauly** [comment]
Hey, after using your bot for a bit we noticed a similar thing would also be really handy for merge requests - to notify if their `action` is open or close and nothing else?
See https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md#merge-request-events

Otherwise you get a notice on every comment, push, and so on for each PR

**Comment by Requilence** [comment]
Hey @mpauly, I implemented and deployed the both features: filter for Merge request and CI events. Just send the `/settings` command to @gitlab_bot. And please give me a feedback :)

**Comment by mpauly** [comment]
@Requilence  works for us, thank you!
