### ISSUE TITLE
Trello Bot uses old username.

### ISSUE THREAD

**Issue by Martin-DAN** [requilence/integram#111]
Hello,

I changed my telegram username a few days ago, but messages from the Bot still using my old one.

How can I resolve this?
Thanks.

**Comment by requilence** [comment]
Hello @Martin-DAN!
The username is cached for some time, but you can speed up the process. Just vote for any of trello card you've got from bot within the telegram. It should trigger the personal info cache update. Let me know if this will help.

BTW, I will tune the username caching later. Thanks for reporting

**Comment by Martin-DAN** [comment]
Yeah thanks @requilence.  It worked \o/
