### ISSUE TITLE
Trello bot doesn't write username in telegram chat

### ISSUE THREAD

**Issue by gosteev** [Requilence/integram#13]
Hello. When i add myself as a member to task, trello bot writes '@gosteev adds @gosteev'  but when i add somebody else, it writes '@gosteev adds Jane Doe', even though that this user has the same username in trello and telegram.
How can i fix that? Thanks.

**Comment by Requilence** [comment]
@gosteev Hi! To avoid wrong username mapping from Trello to Telegram username resolving works only for users authorised on @trello_bot

**Comment by gosteev** [comment]
@Requilence 
![image](https://cloud.githubusercontent.com/assets/6203574/20037930/211cb9c6-a433-11e6-8d65-e90403e8aa3a.png)

Thanks for reply, i'll check it asap!

**Comment by Requilence** [comment]
:) Was the issue solved for you?

**Comment by gosteev** [comment]
@Requilence not really. nothing changed

**Comment by gosteev** [comment]
i will close issue due to low priority at the moment. if somebody will face the same problem - please, reopen
