### ISSUE TITLE
Store files as attachments

### ISSUE THREAD

**Issue by spacediver** [Requilence/integram#14]
1. The user searches for a card in chat, the bot posts a card with a fascinating inline keyboard.
2. The user repleis to card with a message with a photo/voice/document attached.
4. The bot should attach this file to the card.

**Comment by Requilence** [comment]
Hi Pavel,
Unfortunately, this is known behavior as @trello_bot doesn't receive replies from Telegram on messages `Username via @trello_bot `
Hope this will be fixed in the near future.

**Comment by spacediver** [comment]
Telegram does hold these replies from reaching the bot, right? Is this a known limitation of Bot API?

May we, perhaps convert text replies (containing only an URL, for example) into attachments? 

p.s. Using the case to congratulate you with awards.

**Comment by Requilence** [comment]
Just checked this scenario. Looks like Telegram already fixed this limitation. I pushed the fix for [@trello_bot](https://telegram.me/trello_bot)

**Comment by spacediver** [comment]
Works like a charm!

**Comment by Requilence** [comment]
@spacediver Nice 👍 Thanks for the helpful feedback
