### ISSUE TITLE
Comment in specific card via telegram

### ISSUE THREAD

**Issue by aditiapratama** [Requilence/integram#16]
Hi, I wonder how to create comment or attach file via telegram? Is this doable?

thanks

**Comment by Requilence** [comment]
You just need to reply the card's message or card's comment message within Telegram. You can use text or a file.
Maybe I need to add a note about it somewhere besides board integrated message

**Comment by aditiapratama** [comment]
ah yeah, thank you, just realized it just now. thank you I'll close this issue

**Comment by citec** [comment]
Hi @Requilence , how do you comment on a card if I have disabled the notifications? (so I don't have any card message to answer to)

**Comment by Requilence** [comment]
@citec You can search a card, using the inline query in the text box.
Like this: `@trello_bot keyword`
Select the right card. 
Now you can reply to it within the chat

**Comment by citec** [comment]
ok, thanks
