### ISSUE TITLE
[Question] Bot setup

### ISSUE THREAD

**Issue by bosslee** [Requilence/integram#17]
Hi there

thanks for making this open source.
I'm trying to learn and set up
I managed to get this up and running 
![2017-01-20 at 7 08 pm](https://cloud.githubusercontent.com/assets/993948/22147527/eb7707f8-df43-11e6-8d8d-eec83bda56c9.jpg)

But when I type /start with the bot.
an error occured at tgupdates.go

I followed your steps. Is there anything I'm doing wrong?

Thank you

**Comment by Requilence** [comment]
Hi,
Can't reproduce this on my system :(
Could you please pull the last master and send me the output? I improved error logging here.

**Comment by bosslee** [comment]
Thank you
the new error logging help. 
it solved this issue.
I have another question, think I better start another issue to keep it clean.
again thank you so much
