### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by mementor** [Requilence/integram#2]
When I try to execute `go get -v -u github.com/requilence/integram` -- I am getting error:

```
src/github.com/requilence/integram/bots.go:84: undefined: tgbotapi.MessageEntity
src/github.com/requilence/integram/bots.go:94: undefined: tgbotapi.Venue
```

In bots.go import looks like:
```
import (
  ...
  tg "gopkg.in/telegram-bot-api.v3"
)
```

I believe that this types was added in v4.0.0 of tgbotapi (commit: https://github.com/go-telegram-bot-api/telegram-bot-api/commit/18510df3c98b3f96a1326768096b282763b71237)

**Comment by Requilence** [comment]
Hi! Actually I was waiting for this issue 😬 
Noticed this yesterday. There was a bug with vendor dir on my environment.
Now the instruction should works for the clean install
