### ISSUE TITLE
Unable to start Integram

### ISSUE THREAD

**Issue by VanZaant** [Requilence/integram#22]
Hello!
First of all, thanks for development and open sourcing Integram. It's extremely useful.
But,
today I've noticed that Trello messages not handled. So the messages were marked as read, but
without any actions from @trello_bot.
I was trying to restart the @trello_bot and Integram itself but after Integram restart it didn't even suggest me the integration list.

Trying to open Integram via web version of Telegram got the message "One of the params is missing or invalid." with such technical details

`Method: messages.sendMessage
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"YOU_BLOCKED_USER"}`

Didn't found message YOU_BLOCKED_USER in Telegram API docs.

Please, advise how can I debug such case on my side.
Thanks you in advance.

**Comment by VanZaant** [comment]
May be connected with #19

**Comment by Requilence** [comment]
Hi! I fixed the bug that caused this hang issue @22b97fd3e5e5521809897857a1fb58e62fd40903
Could you please confirm?

**Comment by VanZaant** [comment]
@Requilence Yes, a moment ago I was able to get back all the great functionality of Integram!!!
Thank you very much! Incredible support!

**Comment by Requilence** [comment]
Thank you for reporting! 👍

**Comment by VanZaant** [comment]
@Requilence it has been working perfectly for last 7 days, but today issue turned back.
I've noticed that @trello_bot didn't reply to me.  Repeat of the command or perform other command doesn't get a result.  
If I try to restart Integram, it doesn't react to any commands after Start pressed.
Please, advice me and feel free to request my help to investigate the issue.
Thanks in advance.
