### ISSUE TITLE
have problem with bitbucket integrations

### ISSUE THREAD

**Issue by tozik** [Requilence/integram#35]
yo

i cant integrate integram with bitbucket
pushing to /start in integram he is redirect me to bitbucket and after that
he is giving me link for adding in the webhooks to setting
i'm added, saving, and nothing change
whats next i musted make, help please??

**Comment by Requilence** [comment]
Hi! Are you sure that you have selected all events that you need on the webhook setup screen?
I'm not see any problem on the Bitbucket integration right now
<img width="571" alt="screen shot 2017-06-05 at 14 58 51" src="https://cloud.githubusercontent.com/assets/1025231/26786850/d2323d7c-49ff-11e7-9e7d-91529ae80faf.png">

**Comment by tozik** [comment]
http://c2n.me/3L3qdIU
and what next or is it all?

**Comment by Requilence** [comment]
@tozik That's all. Now you should receive notifications about that events in the Telegram

**Comment by tozik** [comment]
Tell me please What notifications I should recive??

**Comment by Requilence** [comment]
@tozik E.g. if you someone creates the issue, pushes to the repo or any other events you have specified on the webhook screen. You will receive the message in the Telegram

**Comment by tozik** [comment]
thanks all is works)
beautiful tool
