### ISSUE TITLE
Does it support newer gitlab api?

### ISSUE THREAD

**Issue by vansteki** [requilence/integram#42]
<img width="350" alt="screen shot 2017-08-30 at 1 01 05 am" src="https://user-images.githubusercontent.com/1705361/29833812-372dadc6-8d1f-11e7-8e0a-cf2aecc3719c.png">

when i use older verison of gitlab (GitLab Community Edition 8.8.2), the word issue can be link to correspond issue URL.
it now worked for the new version of gitlab (GitLab Community Edition 9.2.2)

**Comment by requilence** [comment]
Hi!
Im trying to focus on the latest releases, because most of users are using the cloud version. 
And I'm probably need to specify some recommendation for the Gitlab version.
