### ISSUE TITLE
Gitlab bot per repository

### ISSUE THREAD

**Issue by Damian-Pumar** [requilence/integram#44]
Hi, how i can create one Gitlab bot per repository and assign each a group?

Thanks!
Regards.

**Comment by requilence** [comment]
Hi! Sorry for the long answer. 
Just add [@gitlab_bot](https://t.me/gitlab_bot) to each group in Telegram. It will send you individual Webhook for each group. So you will need to specify them in corresponding repos (they even can be on different gitlab servers)
