### ISSUE TITLE
Self-hosted Bitbucket

### ISSUE THREAD

**Issue by compiaffe** [requilence/integram#5]
The locally hosted version of bitbucket does not have a 'Webhooks' section in the repository settings. It only has a 'Hooks' section which is very limited, allowing only specify plugins to offer outgoing webhooks here. The plugin 

> POST service webhook for Bitbucket Server 

by Atlassian and documented [here](https://confluence.atlassian.com/bitbucketserver/post-service-webhook-for-bitbucket-server-776640367.html) seems the only one offering to send webhooks. However nothing happens when pushing to the branch.

Please integrate the self-hosted bitbucket server into integram.

**Comment by Requilence** [comment]
POST service is also supported by https://github.com/Requilence/integram/blob/master/services/bitbucket/webhook.go#L196
I need to clarify this in bitbucket_bot instructions

**Comment by compiaffe** [comment]
Yes I tried the POST services webhook plugin but on committing and pushing the commits nothing happens in the bitbucket_bot...

**Comment by Requilence** [comment]
You got it right? <img width="330" alt="screen shot 2016-07-29 at 12 05 25" src="https://cloud.githubusercontent.com/assets/1025231/17243347/4f28d79a-558d-11e6-89a3-b9df79415e81.png">

**Comment by compiaffe** [comment]
I'm afraid there is neither a services nor a webhooks in bitbucket server 4.8.3:
![screenshot from 2016-07-31 15-21-30](https://cloud.githubusercontent.com/assets/411223/17276751/a74edacc-5732-11e6-89c0-3cfe0e7cfdcc.png)

**Comment by Requilence** [comment]
I found some [docs](https://confluence.atlassian.com/bitbucketserver/post-service-webhook-for-bitbucket-server-776640367.html) but not sure if this the actual one (the name is different). So I need to check the payloads of this **Post-Receive WebHooks**. If you want to speed up this process please contact me on the telegram – https://telegram.me/requilence

**Comment by stamepicmorg** [comment]
@compiaffe hello! did you found any solution?

**Comment by pySilver** [comment]
Webhooks are available in latest bitbucket 6.3 (since 5.13 I guess) bit despite having webhook setup bot stays silent.

See: 
https://take.ms/jSr0B
https://take.ms/VPPzi
