### ISSUE TITLE
Website resources/assets doesn't load [error 477 (?)]

### ISSUE THREAD

**Issue by arieljannai** [requilence/integram#50]
The website:
![image](https://user-images.githubusercontent.com/3811594/34603899-7daa3e1e-f20e-11e7-9828-a79f15f9ca52.png)

  The console errors:
![image](https://user-images.githubusercontent.com/3811594/34603956-bd00cf38-f20e-11e7-9ce4-0e947e5c24b5.png)

**Comment by requilence** [comment]
Oops, now fixed! Thanks for reporting ☺️

**Comment by arieljannai** [comment]
Thank for the great work!
