### ISSUE TITLE
GitHub integration does not notify about subscribes.

### ISSUE THREAD

**Issue by optimistex** [requilence/integram#55]
I am receiving notification about my projects. But I have notifications from watching projects. 
When I open the GitHub-site I see unread notifications from watching projects, but I have no one notifying in the Telegram.

**Comment by requilence** [comment]
Hi! Unfortunately, [@githubbot](https://t.me/githubbot) is not part of Integram. 
BTW I understand the reason of this behaviour. Github only supports Webhooks for your own private/org repos. There is no way for you to set a Webhook for another repo, even public.

**Comment by optimistex** [comment]
Sadly. But anyway thank you for the answer.
