### ISSUE TITLE
Support for self-hosted Gitlab

### ISSUE THREAD

**Issue by bekir-murat** [requilence/integram#57]
We host our own instance of Gitlab.

I guess this is just a matter of replacing all occurrences of **gitlab.com** in the code by the custom gitlab url.

But there is something that prevents me from trying this : given that gitlab requires a _redirect_uri_ for oauth authentication, it means that gitlab has to be able to access the IP where Integram runs. Which is not the case in our infrastructure.
For Integram to work in our setup, we would need to use gitlab access tokens instead of oauth, which requires quite a lot of changes.

**Comment by requilence** [comment]
Hey! Actually this thing was implemented from the begining. 
You just need to follow the instructions that [@gitlab_bot](https://t.me/gitlab_bot) sends you on /start command:
1. Add the provided webhook URL for your self-hosted gitlab repos
2. When some action happens(issue created, something commited etc.) you will receive the Telegram message from @gitlab_bot
3. When you will try to interact with this issue/commit inside the Telegram chat you will be asked to create the new OAuth app inside your Gitlab instance and provide all details for the bot

Let me know if you will have any questions or troubles by the way.

**Comment by KatSick** [comment]
We using self host GitLab and all works like a charm

**Comment by bekir-murat** [comment]
Cool, thanks for your answers.
So, my understanding is that you use the webhook connector for this instead of the gitlab one. Is that correct ?
Will try to make it work and let you know how it goes.
