### ISSUE TITLE
Not enough details on Gitlab notifications

### ISSUE THREAD

**Issue by bekir-murat** [requilence/integram#58]
Hi,
Thank you for this much needed integration.
Now some of our notifications for issue changes look like this : 
![image](https://user-images.githubusercontent.com/28331897/36568130-23b46344-1829-11e8-834c-b4ed8ee10fd5.png)
I guess that's not how these are supposed to look ?
(We host our Gitlab and our Integram bot)

**Comment by requilence** [comment]
Hi,
Hm... This message should be a reply to the original issue message.. Does it still available in this chat?

**Comment by bekir-murat** [comment]
I think it is just because the issue has been created before we created the bot.
For issues that have been created after the bot, it works as expected (the updates and close are replies to the original issue message as you described).
I just wished the issue name and link would appear in the update in this case.
But honestly this is a minor problem as it works properly with new issues.

**Comment by bekir-murat** [comment]
Closing this as it works properly for most issues. Thanks !
