### ISSUE TITLE
GitHubBot replies "Invalid integration selected." to group events

### ISSUE THREAD

**Issue by hangyas** [requilence/integram#65]
GitHubBot replies "Invalid integration selected." to group events such as new user join, user left, etc. (I guess when message.text is null) I don't know if problem exists for other bots too.

![image](https://user-images.githubusercontent.com/7001368/43189107-1da8858a-8ff6-11e8-8069-9be3acced8cf.png)

**Comment by requilence** [comment]
GithubBot is not made by me, but I forwarded this issue to the maker
