### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by yusufk** [requilence/integram#69]
Tried integrating Trello to Telegram, clicked the auth link:
https://integram.org/oauth1/XXXXXXXXXXX
 and got:
Service not found

**Comment by requilence** [comment]
@yusufk Hello
It should give a link like https://integram.org/tz?r=%2Foauth1%2Ftrello%2Fxxxxxxxx
Maybe this is an old link you requested long time ago? Try to send /reauthorize – bot will send you the new link

**Comment by yusufk** [comment]
Cool, thanks
