### ISSUE TITLE
Ignore invalid commands in groups

### ISSUE THREAD

**Issue by gumblex** [Requilence/integram#8]
If we send some text with command without bot's name, and which is invalid for your bots (but may be valid for other bots), such as `/status`, it will respond with `Command is invalid. Say what?`. This kind of behavior is annoying in group chat.

Please ignore invalid command without bot's name in group chats, so that:
* it won't respond to `/status` in group chats
* it says invalid for `/status@GitHubBot`

**Comment by gumblex** [comment]
Sorry, I didn't notice that @GitHubBot is not the part of Integram.

**Comment by Requilence** [comment]
@gumblex Hi! Good news, this behavior should be fixed now. Thanks goes to https://github.com/zhukov
