### ISSUE TITLE
Intergram for Gitlab is down?

### ISSUE THREAD

**Issue by drajathasan** [requilence/integram#93]
I don't have any push notification from Gitlab Intergram Bot in my project. I think my integration token is wrong, I just try to re-setting again, but bot not respond. 

![image](https://user-images.githubusercontent.com/38057222/72216507-6ec2b300-3554-11ea-9e94-c8f1d696e881.png)

**Comment by requilence** [comment]
> I don't have any push notification from Gitlab Intergram Bot in my project. I think my integration token is wrong, I just try to re-setting again, but bot not respond.

was a problem with the redis queue, have just fixed
